### ISSUE TITLE
Board display broken in firefox

### ISSUE THREAD

**Issue by lctrt** [inderps/reversi-game-in-elm#1]
The board doesn't display properly, there's some split in the middle.

**Comment by inderps** [comment]
Hey Quentin,

Thanks a lot for reporting it. I'm still scratching my head why did this appear on firefox only. 

Basically i have 8 divs each having 8 buttons of equal width and height of as of parent div. And Everything is in %age.
Now If i put any div (disc) inside a button (which is not semantically correct html i know), the parent height increases for some reason in firefox
And giving flex to parent div seems to fix it. 

So currently I added flex to parent div and it now works fine. Though still figuring out what is the problem with the earlier solution
